### ISSUE TITLE
 Source code

### ISSUE THREAD

**Issue by computerimage** [pambros/HMM-3D-Catheter-Tip-Tracking#1]
Hi, HMM-3D-Catheter-Tip-Tracking is interesting, it's a good work. It would be better if the Source code of the method propose is available. Thinks!

**Comment by pambros** [comment]
Hi, Thanks for the interest. I have good news :) It's a coincidence because I was planning to commit it exactly today! By the end of the day, the source code will be there.

**Comment by pambros** [comment]
The source code is now available.
